### PR TITLE
Add GroupsAreSortedRule

### PR DESCRIPTION
**Pull request by finnvoor**
Adds a rule to ensure group children are sorted alphabetically (WIP)

- ~Add support to sort by type instead of name?~ later
- ~Opt in to rule somehow~ config issue
- [x] `sorted()` is different than Xcode "Sort by Name"
  - Xcode: [10, 2, 1] -> [1, 2, 10]
  - Sorted: [10, 2, 1] -> [1, 10, 2]
- [x] `sorted(using: .localizedStandard)` isn't available on linux 🤔 
  - Fixed by creating manually (copied from [swift-foundation](https://github.com/apple/swift-foundation/blob/534a60d5af6205693193f7949234bb0714a1afec/Sources/FoundationInternationalization/String/String%2BSortComparator.swift#L30-L38))

@mattmassicotte feel free to nitpick/replace/overwrite/etc, mostly just was curious how hard it would be to implement (very easy it turns out!)

#7

### CODE REVIEW

**Comment by mattmassicotte** [comment]
🤯 holy macaroni this is awesome

long-term, it is probably going to be difficult to manage a single Xcode project for test input, but I'm very happy to burn that bridge when we get to it.

I think it is completely find to just merge this, if you are ok with it. The opt-in is really part of the whole configuration story. And, the sort-by-type idea is cool, but we can tackle that in the future, if needed.

**Comment by mattmassicotte** [comment]
Wait never mind! I saw that the stock macOS one was modified and thought that's what you were using for testing, but isn't. Let's do this!

**Comment by Finnvoor** [comment]
Sounds good, just want to take a look at that last bullet point I added before merging

**Comment by mattmassicotte** [comment]
Huh, interesting! `sorted(using: .localizedStandard)` isn't available in the Linux version of Foundation. Well this stinks! I assume that kind of comparison is essential for this to work correctly?

**Comment by mattmassicotte** [comment]
Just a little typo missing the use of `sortedChildren`. Easy fix!

**Comment by Finnvoor** [comment]
The comparison sort of needs to be the same on linux, otherwise CI runs will give different errors.  I switched to specifying sort options, but it's unclear to me what is available on linux and what isn't.

**Comment by mattmassicotte** [comment]
> but it's unclear to me what is available on linux and what isn't

I have frequently had this problem too. I tried to help mitigate this by explicitly installing Swift 5.9 on the linux CI instance before running. I think the best thing to do is have a VM set up, but who has time for that. A few back-and-forths with CI is no big deal.

**Comment by iby** [comment]
Hi all! It would be super awesome to have additional configuration on this:

1. Folders on top.
2. Exclude extension.

Just wondering if you've considered that and already given any through to this. If there are any caveats? Happy to work on a separate PR for this, just want to gather some feedback and intel.

**Comment by mattmassicotte** [comment]
@iby Hello! I'd like to better understand what you are after. How are you controlling these two things? I can see manual sorting for folders, but how does exclusing an extension work?

**Pull request merged**
